url: "https://mareksamaj.github.io"
title: Marek Samaj
subtitle: Solutions Architect @Microsoft. Husband, dad, aviator, science fiction fan, homebrewer
description: Marek Samaj - Solutions Architect @Microsoft. Husband, dad, aviator, science fiction fan, homebrewer
theme: minima
